#!/bin/bash
#
#  Copyright (C) 2013-2014 RuneAudio Team
#  http://www.runeaudio.com
#
#  RuneUI
#  copyright (C) 2013-2014 – Andrea Coiutti (aka ACX) & Simone De Gregori (aka Orion)
#
#  RuneOS
#  copyright (C) 2013-2014 – Simone De Gregori (aka Orion) & Carmelo San Giovanni (aka Um3ggh1U)
#
#  RuneAudio website and logo
#  copyright (C) 2013-2014 – ACX webdesign (Andrea Coiutti)
#
#  This Program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3, or (at your option)
#  any later version.
#
#  This Program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with RuneAudio; see the file COPYING.  If not, see
#  <http://www.gnu.org/licenses/gpl-3.0.txt>.
# 
#  file: command/mpd_prio
#  version: 1.3
#  coder: Simone De Gregori
#
#####################################

mpdprio_nice () {
count=1
for pid in $(pgrep -w mpd);
do
        if ((count == 3))
        then
                echo "### Set priority for: mpd-player thread ###";
                renice -15 $pid;
        fi
        if ((count == 4))
        then
                echo "### Set priority for: mpd-output thread ###";
                renice -18 $pid;
        fi
        if ((count == 5))
        then
                echo "### Set priority for: mpd-decoder thread ###";
                renice -16 $pid;
        fi
count=$((count+1))
done
}

mpdprio_default () {
count=1
for pid in $(pgrep -w mpd);
do
        if ((count == 3))
        then
                echo "### Set priority for: mpd-player thread ###";
                renice 20 $pid;
        fi
        if ((count == 4))
        then
                echo "### Set priority for: mpd-output thread ###";
                renice 20 $pid;
        fi
        if ((count == 5))
        then
                echo "### Set priority for: mpd-decoder thread ###";
                renice 20 $pid;
        fi
count=$((count+1))
done
}

if [ "$1" == "default" ]; then
echo "set MPD threads, default priority settings"
mpdprio_default
exit 0
fi

if [ "$1" == "nice" ]; then
echo "set MPD threads, nice priority settings"
mpdprio_nice
exit 0
fi

if [ "$1" == "" ]; then
echo "MPD process priority settings"
echo "Usage: $0 {default|nice}"
exit 1
fi