#!/usr/bin/php
<?php 
/*
 * Copyright (C) 2013-2014 RuneAudio Team
 * http://www.runeaudio.com
 *
 * RuneUI
 * copyright (C) 2013-2014 - Andrea Coiutti (aka ACX) & Simone De Gregori (aka Orion)
 *
 * RuneOS
 * copyright (C) 2013-2014 - Simone De Gregori (aka Orion) & Carmelo San Giovanni (aka Um3ggh1U)
 *
 * RuneAudio website and logo
 * copyright (C) 2013-2014 - ACX webdesign (Andrea Coiutti)
 *
 * This Program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3, or (at your option)
 * any later version.
 *
 * This Program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with RuneAudio; see the file COPYING.  If not, see
 * <http://www.gnu.org/licenses/gpl-3.0.txt>.
 *
 *  file: command/rune_PL_wrk
 *  version: 1.3
 *  coder: Simone De Gregori
 *
 */
// common include
ini_set('display_errors', '1');
ini_set('error_reporting', -1);
ini_set('error_log', '/var/log/runeaudio/rune_PL_wrk.log');
include('/var/www/app/libs/runeaudio.php');
// reset worker logfile
sysCmd('echo "--------------- start: rune_PL_wrk ---------------" > /var/log/runeaudio/rune_PL_wrk.log');
runelog('WORKER rune_PL_wrk START');
// reset forceupdate state
$forceupdate = 1;
// --- WORKER MAIN LOOP --- //
while (1) {
    // Connect to Redis backend
    $redis = new Redis();
    $redis->pconnect('/tmp/redis.sock');
    if ($redis->get('activePlayer') === 'MPD') {
        runelog('rune_PL_wrk: open MPD local UNIX socket');
        $mpd = openMpdSocket('/run/mpd.sock');
        $spop = true;
    }
    if ($redis->get('activePlayer') === 'Spotify') {
        runelog('rune_PL_wrk: open SPOP socket');
        $spop = openSpopSocket('localhost', 6602, 1);
        $mpd = true;
    }
if (!$mpd OR !$spop) {
    // exit script
    // die();
    $forceupdate = 1;
    sleep(3);
} else {
    // MPD playback engine
        if ($redis->get('activePlayer') === 'MPD') {
            if ($forceupdate !== 0) {
                $forceupdate = 0;
                runelog('----------------------------------- FORCE UPDATE -----------------------------------');
                ui_update($redis, $mpd);
            }
            $status = _parseStatusResponse(MpdStatus($mpd));
            // store next songid
            $redis->set('nextsongid', $status['nextsongid']);
            // store "lastsongid"
            $redis->set('lastsongid', $status['songid']);
            $redis->set('pl_length', $status['playlistlength']);
            // check for Ramplay
            // if ($redis->get('ramplay') === '1') {
                // check ramplay delete
                    // if (!rp_checkPLid($_SESSION['lastsongid'],$mpd)) {
                    // rp_deleteFile($_SESSION['lastsongid'],$mpd);
                    // }
                // check for CMediaFix
                // if ($redis->get('cmediafix') === '1') {
                // $redis->set('lastbitdepth',$status['audio']);
                // }
            // }
            // idle LOOP
            runelog('rune_PL_wrk: enter idle loop');
            $status = monitorMpdState($mpd);
            // idle LOOP
            $redis->set('pl_length', $status['playlistlength']);
            // runelog('---------status data------------',$status);
            $status = ui_status($mpd, $status);
            // runelog('---------status data(2)------------',$status);
            // render Queue (push async)
            // if ($status['changed'] === 'playlist') {
            // $queue = new ui_renderQueue($mpd);
            // $queue->start();
            // runelog('---------------- PLAYLIST RENDER ----------------');
            // }
            // CMediaFix
            if ($redis->get('cmediafix') === '1' && $status['state'] === 'play' ) {
                $status['lastbitdepth'] = $redis->get('lastbitdepth');
                    if ($redis->get('lastbitdepth') !== $status['audio']) {
                        sendMpdCommand($mpd, 'cmediafix');
                    }
            }
            // Ramplay
            // if ($redis->get('ramplay') === '1') {
                    // set consume mode ON
                    // if ($status['consume'] == 0) {
                    // sendMpdCommand($mpd,'consume 1');
                    // $status['consume'] = 1;
                    // }
                // copy track in /dev/shm
                // $path = rp_copyFile($status['nextsongid'],$mpd);
                // exec update mdp locazione ramplay
                // rp_updateFolder($mpd);
                // exec addandplay track
                // rp_addPlay($path,$mpd,$status['playlistlength']);
            // }
            // Global Random
            if (($redis->get('globalrandom') === '1') && ($redis->get('lastsongid') != $status['songid']) && ($redis->get('lock_globalrandom') === '0')) {
                $addsong = new globalRandom($status);
                $addsong->start();
                $redis->set('lock_globalrandom', 1);
            } else {
                $redis->set('lock_globalrandom', 0);
            }
            // JSON response for GUI
            runelog('rune_PL_wrk: ui_render() response', json_encode($status));
            ui_render('playback', json_encode($status));
            // close Redis connection
            $redis->close();
            runelog('rune_PL_wrk: close MPD local UNIX socket');
            closeMpdSocket($mpd);
        }
        // Spotify playback engine
        if ($redis->get('activePlayer') === 'Spotify') {
            if ($forceupdate !== 0) {
                $forceupdate = 0;
                runelog('----------------------------------- FORCE UPDATE -----------------------------------');
                ui_update($redis, $spop);
            }
            // $status = _parseSpopStatusResponse(spopStatus($spop));
            $status =  json_encode(monitorSpopState($spop));
            ui_render('playback', $status);
            runelog('rune_PL_wrk: UI JSON', $status);
            runelog('rune_PL_wrk: close SPOP socket');
            closeSpopSocket($spop);
        }
    // close Redis connection
    $redis->close();
    }
// --- WORKER MAIN LOOP --- //
}
