#!/usr/bin/php
<?php 
/*
 * Copyright (C) 2013-2014 RuneAudio Team
 * http://www.runeaudio.com
 *
 * RuneUI
 * copyright (C) 2013-2014 - Andrea Coiutti (aka ACX) & Simone De Gregori (aka Orion)
 *
 * RuneOS
 * copyright (C) 2013-2014 - Simone De Gregori (aka Orion) & Carmelo San Giovanni (aka Um3ggh1U)
 *
 * RuneAudio website and logo
 * copyright (C) 2013-2014 - ACX webdesign (Andrea Coiutti)
 *
 * This Program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3, or (at your option)
 * any later version.
 *
 * This Program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with RuneAudio; see the file COPYING.  If not, see
 * <http://www.gnu.org/licenses/gpl-3.0.txt>.
 *
 *  file: command/update_os
 *  version: 0.1
 *  coder: Frank Friedmann
 *
 */

function updateOS()
{
    sysCmd('cp /srv/http/app/config/_os/usr/lib/systemd/system/rune_SY_wrk.service /usr/lib/systemd/system/');
    sysCmd('cp /srv/http/app/config/_os/usr/lib/systemd/system/rune_PL_wrk.service /usr/lib/systemd/system/');
    sysCmd('cp /srv/http/app/config/_os/usr/lib/systemd/system/redis.service /usr/lib/systemd/system/');
    sysCmd('cp /srv/http/app/config/_os/usr/lib/systemd/system/mpd.service /usr/lib/systemd/system/');
    sysCmd('cp /srv/http/app/config/_os/usr/lib/systemd/system/ntpd.service /usr/lib/systemd/system/');
    sysCmd('cp /srv/http/app/config/_os/usr/lib/systemd/system/php-fpm.service /usr/lib/systemd/system/');
    sysCmd('systemctl daemon-reload');
    
    sysCmd('rm /etc/netctl/wlan0');

    sysCmd('cp /srv/http/app/config/_os/etc/wpa_supplicant/wpa_supplicant.conf /etc/wpa_supplicant/');

    sysCmd('rm /srv/http/command/update_os');
}
